Repository esdc-devcop/esdc-devcop.github.io, pull requests merged in 2019-09, with the labels that each got.

#26 Adding recommended tools doc
  README.md
  recommendation/tools.md
Labels: documentation, tools

#27 Git guide improvements
  guides/tfvc-to-git.md
Labels: documentation, process

#28 Gccode improve guide
  guides/tfs-to-gccode.md
Labels: documentation, process

#30 Re-working the home page format
  README.md
Labels: documentation

#31 Fix the broken recommendations table
  recommendation/tools.md
Labels: bug, documentation

#32 Change Wiki documenation usage
  guides/tfvc-to-git.md
Labels: documentation, question

#39 Adding back content from strategy
  strategy.md
Labels: bug

#43 Add future dates
  dates.md
  strategy.md
Labels: documentation
