Repository esdc-devcop/esdc-devcop.github.io, pull requests merged in 2019-11, with the labels that each got.

#65 Updates links to docs
  README.md
  strategy/dates.md
Labels: recommendation

#66 Added suggested training to references.
  README.md
  references/suggested-training.md
Labels: documentation, refrences

#67 Create DeveloperServices.md
  References/DeveloperServices.md
Labels: refrences

#74 Adding a menu
  _data/nav.yml
  _layouts/default.html
Labels: documentation

#76 Cleanup
  README.md
  index.md
Labels: documentation

#75 Adding december session
  strategy/dates.md
Labels: topic

#78 Fix link
  index.md
Labels: bug, documentation

#79 Change link to html
  index.md
Labels: bug, documentation
