Repository esdc-devcop/esdc-devcop.github.io, pull requests merged in 2020-01, with the labels that each got.

#92 Updating dates with scheduled events
  strategy/dates.md
Labels: documentation

#94 Adding Jan 2020 Part 1 presentation link
  strategy/dates.md
Labels: documentation, topic

#96 Updating Next Event to ADO
  strategy/dates.md
Labels: topic
